# -*- coding: utf-8 -*-
import unittest
import sys
import os
DIR_NAME = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))))
sys.path.append(DIR_NAME)

from common.utils.utils import Utils
from Project.lottery.apis.testcases.uiapi.uiapi_web_testcases import UiApiWebTestCases
import common.utils.globalvar as gl

# Test Setting
brand = 'lv'
user = 2


# TestCase Setting
api_testcase_list = [
    UiApiWebTestCases("test_web_login"),
    UiApiWebTestCases("test_register"),
    UiApiWebTestCases("test_withdraw"),
    UiApiWebTestCases("test_bg_lottery_game"),
    UiApiWebTestCases("test_ky_qipai_game"),
    UiApiWebTestCases("test_vg_qipai_game"),
    UiApiWebTestCases("test_gm_qipai_game"),
    UiApiWebTestCases("test_lc_qipai_game"),
    UiApiWebTestCases("test_bs_qipai_game"),
    UiApiWebTestCases("test_fg_qipai_game"),
    UiApiWebTestCases("test_kk_qipai_game"),
    UiApiWebTestCases("test_mg_electron_game"),
    UiApiWebTestCases("test_ag_electron_game"),
    UiApiWebTestCases("test_cq_electron_game"),
    UiApiWebTestCases("test_dt_electron_game"),
    UiApiWebTestCases("test_pt_electron_game"),
    UiApiWebTestCases("test_bbin_electron_game"),
    UiApiWebTestCases("test_sb_electron_game"),
    UiApiWebTestCases("test_fg_electron_game"),
    UiApiWebTestCases("test_sw_electron_game"),
    UiApiWebTestCases("test_bg_video_game"),
    UiApiWebTestCases("test_dg_video_game"),
    UiApiWebTestCases("test_ag_video_game"),
    UiApiWebTestCases("test_bbin_video_game"),
    UiApiWebTestCases("test_mg_occident_game"),
    UiApiWebTestCases("test_mg_asia_game"),
    # UiApiWebTestCases("test_gc_video_game"), # 目前"GC_視訊"都是維護狀態
    UiApiWebTestCases("test_bs_fish_game"),
    UiApiWebTestCases("test_bs_fish2_game"),
    UiApiWebTestCases("test_cq_fish_game"),
    UiApiWebTestCases("test_ag_fish_game"),
    UiApiWebTestCases("test_bbin_fish_game"),
    UiApiWebTestCases("test_bs_fish3_game"),
    UiApiWebTestCases("test_bbin_fish2_game"),
    UiApiWebTestCases("test_bs_fish4_game"),
    UiApiWebTestCases("test_cq_fish3_game"),
    # UiApiWebTestCases("test_pt_fish_game"),  # 目前PT捕魚沒有遊戲
    UiApiWebTestCases("test_bbin_fish3_game"),
    UiApiWebTestCases("test_bbin_fish4_game"),
    UiApiWebTestCases("test_saba_sport_game"),
    UiApiWebTestCases("test_bbin_sport_game"),
    UiApiWebTestCases("test_hg_sport_game"),
    UiApiWebTestCases("test_ss_sport_game"),
    UiApiWebTestCases("test_return_cp"),
    UiApiWebTestCases("test_cp_to_ag"),
    UiApiWebTestCases("test_cp_to_mg"),
    UiApiWebTestCases("test_cp_to_sb"),
    UiApiWebTestCases("test_cp_to_bbin"),
    UiApiWebTestCases("test_cp_to_3s"),
    UiApiWebTestCases("test_cp_to_dt"),
    # UiApiWebTestCases("test_cp_to_gc"), # 目前"GC_視訊"都是維護狀態
    UiApiWebTestCases("test_cp_to_ky"),
    UiApiWebTestCases("test_cp_to_vg"),
    UiApiWebTestCases("test_cp_to_sw"),
    UiApiWebTestCases("test_cp_to_pt"),
    UiApiWebTestCases("test_cp_to_lc"),
    UiApiWebTestCases("test_cp_to_hg"),
    UiApiWebTestCases("test_cp_to_gm"),
    UiApiWebTestCases("test_cp_to_fg"),
    UiApiWebTestCases("test_cp_to_dg"),
    UiApiWebTestCases("test_cp_to_cq9"),
    UiApiWebTestCases("test_cp_to_bsp"),
    UiApiWebTestCases("test_cp_to_kk"),
    UiApiWebTestCases("test_cp_to_bg"),
    UiApiWebTestCases("test_change_login_password"),
    UiApiWebTestCases("test_change_security_password"),
    UiApiWebTestCases("test_change_contact"),
    UiApiWebTestCases("test_change_bank_card"),
    UiApiWebTestCases("lottery_order_special_number"),
    UiApiWebTestCases("lottery_order_special_two_sides"),
    UiApiWebTestCases("lottery_order_special_teshaw"),
    UiApiWebTestCases("lottery_order_special_he_xiao"),
    UiApiWebTestCases("lottery_order_special_head_count"),
    UiApiWebTestCases("lottery_order_special_mantissa"),
    UiApiWebTestCases("lottery_order_special_five_elements"),
    UiApiWebTestCases("lottery_order_positive_number"),
    UiApiWebTestCases("lottery_order_positive_sum"),
    UiApiWebTestCases("lottery_order_positive_zheng_xiao"),
    UiApiWebTestCases("lottery_order_positive_chief_shaw"),
    UiApiWebTestCases("lottery_order_positive_special_one_number"),
    UiApiWebTestCases("lottery_order_positive_special_one_two_sides"),
    UiApiWebTestCases("lottery_order_positive_special_one_color"),
    UiApiWebTestCases("lottery_order_positive_special_two_number"),
    UiApiWebTestCases("lottery_order_positive_special_two_two_sides"),
    UiApiWebTestCases("lottery_order_positive_special_two_color"),
    UiApiWebTestCases("lottery_order_positive_special_three_number"),
    UiApiWebTestCases("lottery_order_positive_special_three_two_sides"),
    UiApiWebTestCases("lottery_order_positive_special_three_color"),
    UiApiWebTestCases("lottery_order_positive_special_four_number"),
    UiApiWebTestCases("lottery_order_positive_special_four_two_sides"),
    UiApiWebTestCases("lottery_order_positive_special_four_color"),
    UiApiWebTestCases("lottery_order_positive_special_five_number"),
    UiApiWebTestCases("lottery_order_positive_special_five_two_sides"),
    UiApiWebTestCases("lottery_order_positive_special_five_color"),
    UiApiWebTestCases("lottery_order_positive_special_six_number"),
    UiApiWebTestCases("lottery_order_positive_special_six_two_sides"),
    UiApiWebTestCases("lottery_order_positive_special_six_color"),
    UiApiWebTestCases("lottery_order_pinshaw_tail_one_tail"),
    UiApiWebTestCases("lottery_order_pinshaw_tail_yi_xiao"),
    UiApiWebTestCases("lottery_order_lian_xiao_lian_tail_two_tail"),
    UiApiWebTestCases("lottery_order_lian_xiao_lian_tail_three_tail"),
    UiApiWebTestCases("lottery_order_lian_xiao_lian_tail_four_tail"),
    UiApiWebTestCases("lottery_order_lian_xiao_lian_tail_five_tail"),
    UiApiWebTestCases("lottery_order_lian_xiao_lian_tail_two_xiao"),
    UiApiWebTestCases("lottery_order_lian_xiao_lian_tail_three_xiao"),
    UiApiWebTestCases("lottery_order_lian_xiao_lian_tail_four_xiao"),
    UiApiWebTestCases("lottery_order_lian_xiao_lian_tail_five_xiao"),
    UiApiWebTestCases("lottery_order_consecutive_number_special"),
    UiApiWebTestCases("lottery_order_consecutive_number_two_special_win"),
    UiApiWebTestCases("lottery_order_consecutive_number_two_all_win"),
    UiApiWebTestCases("lottery_order_consecutive_number_three_win_two"),
    UiApiWebTestCases("lottery_order_consecutive_number_three_all_win"),
    UiApiWebTestCases("lottery_order_consecutive_number_four_all_win"),
    UiApiWebTestCases("lottery_order_not_win_five_not_win"),
    UiApiWebTestCases("lottery_order_not_win_six_not_win"),
    UiApiWebTestCases("lottery_order_not_win_seven_not_win"),
    UiApiWebTestCases("lottery_order_not_win_eight_not_win"),
    UiApiWebTestCases("lottery_order_not_win_nine_not_win"),
    UiApiWebTestCases("lottery_order_not_win_ten_not_win"),
    UiApiWebTestCases("lottery_order_not_win_eleven_not_win"),
    UiApiWebTestCases("lottery_order_not_win_twelve_not_win"),
    UiApiWebTestCases("lottery_order_sb_sb"),
    UiApiWebTestCases("lottery_order_sb_bb"),
    UiApiWebTestCases("lottery_order_sb_bbb"),
    UiApiWebTestCases("lottery_order_sb_seven_sb"),
    UiApiWebTestCases("lottery_order_win_five_win_one"),
    UiApiWebTestCases("lottery_order_win_six_win_one"),
    UiApiWebTestCases("lottery_order_win_seven_win_one"),
    UiApiWebTestCases("lottery_order_win_eight_win_one"),
    UiApiWebTestCases("lottery_order_win_nine_win_one"),
    UiApiWebTestCases("lottery_order_win_ten_win_one"),
    UiApiWebTestCases("ssc_order_two_sides_ten_thousand"),
    UiApiWebTestCases("ssc_order_two_sides_thousand"),
    UiApiWebTestCases("ssc_order_two_sides_hundred"),
    UiApiWebTestCases("ssc_order_two_sides_ten"),
    UiApiWebTestCases("ssc_order_two_sides_one"),
    UiApiWebTestCases("ssc_order_sum"),
    UiApiWebTestCases("ssc_order_sum_mantissa"),
    UiApiWebTestCases("ssc_order_long_hu_he"),
    UiApiWebTestCases("ssc_order_sum_five_characters"),
    UiApiWebTestCases("ssc_order_sum_top_three"),
    UiApiWebTestCases("ssc_order_sum_middle_three"),
    UiApiWebTestCases("ssc_order_sum_last_three"),
    UiApiWebTestCases("ssc_order_sum_ten_thousand_thousand"),
    UiApiWebTestCases("ssc_order_sum_ten_thousand_hundred"),
    UiApiWebTestCases("ssc_order_sum_ten_thousand_ten"),
    UiApiWebTestCases("ssc_order_sum_ten_thousand_one"),
    UiApiWebTestCases("ssc_order_sum_thousand_hundred"),
    UiApiWebTestCases("ssc_order_sum_thousand_ten"),
    UiApiWebTestCases("ssc_order_sum_thousand_one"),
    UiApiWebTestCases("ssc_order_sum_hundred_ten"),
    UiApiWebTestCases("ssc_order_sum_hundred_one"),
    UiApiWebTestCases("ssc_order_sum_ten_one"),
    UiApiWebTestCases("ssc_order_sum_mantissa_five_characters"),
    UiApiWebTestCases("ssc_order_sum_mantissa_top_three"),
    UiApiWebTestCases("ssc_order_sum_mantissa_middle_three"),
    UiApiWebTestCases("ssc_order_sum_mantissa_last_three"),
    UiApiWebTestCases("ssc_order_sum_mantissa_ten_thousand_thousand"),
    UiApiWebTestCases("ssc_order_sum_mantissa_ten_thousand_hundred"),
    UiApiWebTestCases("ssc_order_sum_mantissa_ten_thousand_ten"),
    UiApiWebTestCases("ssc_order_sum_mantissa_ten_thousand_one"),
    UiApiWebTestCases("ssc_order_sum_mantissa_thousand_hundred"),
    UiApiWebTestCases("ssc_order_sum_mantissa_thousand_ten"),
    UiApiWebTestCases("ssc_order_sum_mantissa_thousand_one"),
    UiApiWebTestCases("ssc_order_sum_mantissa_hundred_ten"),
    UiApiWebTestCases("ssc_order_sum_mantissa_hundred_one"),
    UiApiWebTestCases("ssc_order_sum_mantissa_ten_one"),
    UiApiWebTestCases("ssc_order_choose_one_all_five"),
    UiApiWebTestCases("ssc_order_choose_one_top_three"),
    UiApiWebTestCases("ssc_order_choose_one_middle_three"),
    UiApiWebTestCases("ssc_order_choose_one_last_three"),
    UiApiWebTestCases("ssc_order_word_positioning_ten_thousand"),
    UiApiWebTestCases("ssc_order_word_positioning_thousand"),
    UiApiWebTestCases("ssc_order_word_positioning_hundred"),
    UiApiWebTestCases("ssc_order_word_positioning_ten"),
    UiApiWebTestCases("ssc_order_word_positioning_one"),
    UiApiWebTestCases("ssc_order_twoword_positioning_ten_thousand_thousand"),
    UiApiWebTestCases("ssc_order_twoword_positioning_ten_thousand_hundred"),
    UiApiWebTestCases("ssc_order_twoword_positioning_ten_thousand_ten"),
    UiApiWebTestCases("ssc_order_twoword_positioning_ten_thousand_one"),
    UiApiWebTestCases("ssc_order_twoword_positioning_thousand_hundred"),
    UiApiWebTestCases("ssc_order_twoword_positioning_thousand_ten"),
    UiApiWebTestCases("ssc_order_twoword_positioning_thousand_one"),
    UiApiWebTestCases("ssc_order_twoword_positioning_hundred_ten"),
    UiApiWebTestCases("ssc_order_twoword_positioning_hundred_one"),
    UiApiWebTestCases("ssc_order_twoword_positioning_ten_one"),
    UiApiWebTestCases("ssc_order_threeword_positioning_top_three"),
    UiApiWebTestCases("ssc_order_threeword_positioning_middle_three"),
    UiApiWebTestCases("ssc_order_threeword_positioning_last_three"),
    UiApiWebTestCases("ssc_order_fiveword_positioning"),
    UiApiWebTestCases("ssc_order_group_three_top_three"),
    UiApiWebTestCases("ssc_order_group_three_middle_three"),
    UiApiWebTestCases("ssc_order_group_three_last_three"),
    UiApiWebTestCases("ssc_order_group_six_top_three"),
    UiApiWebTestCases("ssc_order_group_six_middle_three"),
    UiApiWebTestCases("ssc_order_group_six_last_three"),
    UiApiWebTestCases("ssc_order_span_top_three"),
    UiApiWebTestCases("ssc_order_span_middle_three"),
    UiApiWebTestCases("ssc_order_span_last_three"),
    UiApiWebTestCases("ssc_order_special_play_top_three"),
    UiApiWebTestCases("ssc_order_special_play_middle_three"),
    UiApiWebTestCases("ssc_order_special_play_last_three"),
    UiApiWebTestCases("pk_ten_order_champion"),
    UiApiWebTestCases("pk_ten_order_runner_up"),
    UiApiWebTestCases("pk_ten_order_third_place"),
    UiApiWebTestCases("pk_ten_order_fourth_place"),
    UiApiWebTestCases("pk_ten_order_fifth_place"),
    UiApiWebTestCases("pk_ten_order_sixth_place"),
    UiApiWebTestCases("pk_ten_order_seventh_place"),
    UiApiWebTestCases("pk_ten_order_eighth_place"),
    UiApiWebTestCases("pk_ten_order_ninth_place"),
    UiApiWebTestCases("pk_ten_order_tenth_place"),
    UiApiWebTestCases("pk_ten_order_champion_and_runner_up_number"),
    UiApiWebTestCases("pk_ten_order_champion_and_runner_up_two_sides"),
    UiApiWebTestCases("pk_ten_order_champion_vs_tenth_place"),
    UiApiWebTestCases("pk_ten_order_runner_up_vs_ninth_place"),
    UiApiWebTestCases("pk_ten_order_third_vs_eighth_place"),
    UiApiWebTestCases("pk_ten_order_fourth_vs_seventh_place"),
    UiApiWebTestCases("pk_ten_order_fifth_vs_sixth_place"),
    UiApiWebTestCases("pc_egg_order_special_number"),
    UiApiWebTestCases("pc_egg_order_special_package_three"),
    UiApiWebTestCases("pc_egg_order_two_sides"),
    UiApiWebTestCases("pc_egg_order_sb"),
    UiApiWebTestCases("pc_egg_order_special"),
    UiApiWebTestCases("eleven_choice_five_order_sum"),
    UiApiWebTestCases("eleven_choice_five_order_two_sides_first_ball"),
    UiApiWebTestCases("eleven_choice_five_order_two_sides_secend_ball"),
    UiApiWebTestCases("eleven_choice_five_order_two_sides_third_ball"),
    UiApiWebTestCases("eleven_choice_five_order_two_sides_fourth_ball"),
    UiApiWebTestCases("eleven_choice_five_order_two_sides_fifth_ball"),
    UiApiWebTestCases("eleven_choice_five_order_single_code_first_ball"),
    UiApiWebTestCases("eleven_choice_five_order_single_code_second_ball"),
    UiApiWebTestCases("eleven_choice_five_order_single_code_third_ball"),
    UiApiWebTestCases("eleven_choice_five_order_single_code_fourth_ball"),
    UiApiWebTestCases("eleven_choice_five_order_single_code_fifth_ball"),
    UiApiWebTestCases("eleven_choice_five_order_optional_one_in_one"),
    UiApiWebTestCases("eleven_choice_five_order_optional_two_in_two"),
    UiApiWebTestCases("eleven_choice_five_order_optional_three_in_three"),
    UiApiWebTestCases("eleven_choice_five_order_optional_four_in_four"),
    UiApiWebTestCases("eleven_choice_five_order_optional_five_in_five"),
    UiApiWebTestCases("eleven_choice_five_order_optional_six_in_five"),
    UiApiWebTestCases("eleven_choice_five_order_optional_seven_in_five"),
    UiApiWebTestCases("eleven_choice_five_order_optional_eight_in_five"),
    UiApiWebTestCases("eleven_choice_five_order_group_selection_top_two"),
    UiApiWebTestCases("eleven_choice_five_order_group_selection_top_three"),
    UiApiWebTestCases("eleven_choice_five_order_direct_selection_top_two"),
    UiApiWebTestCases("eleven_choice_five_order_direct_selection_top_three"),
    UiApiWebTestCases("k_three_order_two_sides"),
    UiApiWebTestCases("k_three_order_point"),
    UiApiWebTestCases("k_three_order_three_armies"),
    UiApiWebTestCases("k_three_order_round_dice"),
    UiApiWebTestCases("k_three_order_long_card"),
    UiApiWebTestCases("k_three_order_short_card"),
    UiApiWebTestCases("normal_lottery_order_word_positioning_hundred"),
    UiApiWebTestCases("normal_lottery_order_word_positioning_ten"),
    UiApiWebTestCases("normal_lottery_order_word_positioning_one"),
    UiApiWebTestCases("normal_lottery_order_two_star_group_selection"),
    UiApiWebTestCases("normal_lottery_order_three_star_group_selection_three"),
    UiApiWebTestCases("normal_lottery_order_three_star_group_selection_six"),
    UiApiWebTestCases("normal_lottery_order_word_parley"),
    UiApiWebTestCases("normal_lottery_order_sum"),
    UiApiWebTestCases("normal_lottery_order_sum_mantissa"),
    UiApiWebTestCases("normal_lottery_order_span"),
    UiApiWebTestCases("normal_lottery_order_longhuhe"),
    UiApiWebTestCases("normal_lottery_order_three_star_special"),
    UiApiWebTestCases("check_lottery_amff6_bet_record"),
    UiApiWebTestCases("check_lottery_amsf6_bet_record"),
    UiApiWebTestCases("check_lottery_amwf6_bet_record"),
    UiApiWebTestCases("check_lottery_ff6_bet_record"),
    UiApiWebTestCases("check_lottery_sf6_bet_record"),
    UiApiWebTestCases("check_lottery_js6_bet_record"),
    UiApiWebTestCases("check_lottery_hk_bet_record"),
    UiApiWebTestCases("check_ssc_jsssc_bet_record"),
    UiApiWebTestCases("check_ssc_wfssc_bet_record"),
    UiApiWebTestCases("check_pk_ten_jspk10_bet_record"),
    UiApiWebTestCases("check_pk_ten_wfpk10_bet_record"),
    UiApiWebTestCases("check_pk_ten_malxyft_bet_record"),
    UiApiWebTestCases("check_pc_egg_fcxy28_bet_record"),
    UiApiWebTestCases("check_pc_egg_jndbsxy28_bet_record"),
    UiApiWebTestCases("check_pc_egg_twxy28_bet_record"),
    UiApiWebTestCases("check_pc_egg_wfxy28_bet_record"),
    UiApiWebTestCases("check_k_three_jisuk3_bet_record"),
    UiApiWebTestCases("check_k_three_wfk3_bet_record"),
    UiApiWebTestCases("check_normal_lottery_fc3d_bet_record"),
    UiApiWebTestCases("check_normal_lottery_pl3_bet_record"),
]

# TestCase frame add
suite = unittest.TestSuite()

if __name__ == "__main__":
    env = 'prod'
    gl._init()
    
    # 以CMD方式執行
    if len(sys.argv) == 1:
        pass
    elif len(sys.argv) > 2:
        data = sys.argv[4].split(',,')
        env = data[0]
        brand = data[1]
        user = data[2]

    gl.set_value('ENV', env)
    gl.set_value('BRAND', brand)
    gl.set_value('USER', int(user))

    # TestCase add
    suite.addTests(api_testcase_list)

    # RuningTest
    Utils.unittest_xml(suite)
    