# -*- coding: utf-8 -*-
import unittest
import sys
import os
DIR_NAME = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))))
sys.path.append(DIR_NAME)

from common.utils.utils import Utils
from Project.lottery.apis.testcases.uiapi.uiapi_web_testcases import UiApiWebTestCases
from Project.lottery.apis.testcases.uiapi.uiapi_admin_testcases import UiApiAdminTestCases
import common.utils.globalvar as gl
from jira.config.base_key import BaseKey

# Test Setting
brand = 'lv'
user = 2
test_type = 'web_api'
push = True # 將結果推倒jira,預設請給予 True

# TestCase Setting
api_web_testcase_list = [
    UiApiWebTestCases("test_web_login"),
    UiApiWebTestCases("test_wap_login"),
    UiApiWebTestCases("test_reseller_login"),
    UiApiWebTestCases("test_cmweb_login"),
    UiApiWebTestCases("test_dwh_login"),
    UiApiWebTestCases("test_mynah_admin_login"),
    UiApiWebTestCases("test_mynah_web"),
    UiApiWebTestCases("test_register"),
    UiApiAdminTestCases("test_set_charge"),
    UiApiWebTestCases("test_desposit_onlinepay"),
    UiApiWebTestCases("test_desposit_unionpay"),
    UiApiWebTestCases("test_desposit_jdpay"),
    UiApiWebTestCases("test_company_deposit"),
    UiApiWebTestCases("test_alipay_qrcode"),
    UiApiWebTestCases("test_alipay_transfer"),
    UiApiWebTestCases("test_weixin_qrcode"),
    UiApiWebTestCases("test_weixin_transfer"),
    UiApiWebTestCases("test_withdraw"),
    UiApiWebTestCases("test_bg_lottery_game"),
    UiApiWebTestCases("test_ky_qipai_game"),
    UiApiWebTestCases("test_vg_qipai_game"),
    UiApiWebTestCases("test_gm_qipai_game"),
    UiApiWebTestCases("test_lc_qipai_game"),
    UiApiWebTestCases("test_bs_qipai_game"),
    UiApiWebTestCases("test_fg_qipai_game"),
    UiApiWebTestCases("test_kk_qipai_game"),
    UiApiWebTestCases("test_mg_electron_game"),
    UiApiWebTestCases("test_ag_electron_game"),
    UiApiWebTestCases("test_cq_electron_game"),
    UiApiWebTestCases("test_dt_electron_game"),
    UiApiWebTestCases("test_pt_electron_game"),
    UiApiWebTestCases("test_bbin_electron_game"),
    UiApiWebTestCases("test_sb_electron_game"),
    UiApiWebTestCases("test_fg_electron_game"),
    UiApiWebTestCases("test_sw_electron_game"),
    UiApiWebTestCases("test_bg_video_game"),
    UiApiWebTestCases("test_dg_video_game"),
    UiApiWebTestCases("test_ag_video_game"),
    UiApiWebTestCases("test_bbin_video_game"),
    UiApiWebTestCases("test_mg_occident_game"),
    UiApiWebTestCases("test_mg_asia_game"),
    # UiApiWebTestCases("test_gc_video_game"), # 目前"GC_視訊"都是維護狀態
    UiApiWebTestCases("test_bs_fish_game"),
    UiApiWebTestCases("test_bs_fish2_game"),
    UiApiWebTestCases("test_cq_fish_game"),
    UiApiWebTestCases("test_ag_fish_game"),
    UiApiWebTestCases("test_bbin_fish_game"),
    UiApiWebTestCases("test_bs_fish3_game"),
    UiApiWebTestCases("test_bbin_fish2_game"),
    UiApiWebTestCases("test_bs_fish4_game"),
    UiApiWebTestCases("test_cq_fish3_game"),
    # UiApiWebTestCases("test_pt_fish_game"),  # 目前PT捕魚沒有遊戲
    UiApiWebTestCases("test_bbin_fish3_game"),
    UiApiWebTestCases("test_bbin_fish4_game"),
    UiApiWebTestCases("test_saba_sport_game"),
    UiApiWebTestCases("test_bbin_sport_game"),
    UiApiWebTestCases("test_hg_sport_game"),
    UiApiWebTestCases("test_ss_sport_game"),
    UiApiWebTestCases("test_return_cp"),
    UiApiWebTestCases("test_cp_to_ag"),
    UiApiWebTestCases("test_cp_to_mg"),
    UiApiWebTestCases("test_cp_to_sb"),
    UiApiWebTestCases("test_cp_to_bbin"),
    UiApiWebTestCases("test_cp_to_3s"),
    UiApiWebTestCases("test_cp_to_dt"),
    # UiApiWebTestCases("test_cp_to_gc"), # 目前"GC_視訊"都是維護狀態
    UiApiWebTestCases("test_cp_to_ky"),
    UiApiWebTestCases("test_cp_to_vg"),
    UiApiWebTestCases("test_cp_to_sw"),
    UiApiWebTestCases("test_cp_to_pt"),
    UiApiWebTestCases("test_cp_to_lc"),
    UiApiWebTestCases("test_cp_to_hg"),
    UiApiWebTestCases("test_cp_to_gm"),
    UiApiWebTestCases("test_cp_to_fg"),
    UiApiWebTestCases("test_cp_to_dg"),
    UiApiWebTestCases("test_cp_to_cq9"),
    UiApiWebTestCases("test_cp_to_bsp"),
    UiApiWebTestCases("test_cp_to_kk"),
    UiApiWebTestCases("test_cp_to_bg"),
    UiApiWebTestCases("test_change_login_password"),
    UiApiWebTestCases("test_change_security_password"),
    # UiApiWebTestCases("test_change_contact"), # 暫時不使用,因為目前前台綁定過資料後不給修改
    # UiApiWebTestCases("test_change_bank_card"), # 暫時不使用,因為增加了卡號驗證且會驗證重複卡號問題
    UiApiWebTestCases("test_station_news"),
    UiApiWebTestCases("lottery_order_special_number"),
    UiApiWebTestCases("lottery_order_special_two_sides"),
    UiApiWebTestCases("lottery_order_special_teshaw"),
    UiApiWebTestCases("lottery_order_special_he_xiao"),
    UiApiWebTestCases("lottery_order_special_head_count"),
    UiApiWebTestCases("lottery_order_special_mantissa"),
    UiApiWebTestCases("lottery_order_special_five_elements"),
    UiApiWebTestCases("lottery_order_positive_number"),
    UiApiWebTestCases("lottery_order_positive_sum"),
    UiApiWebTestCases("lottery_order_positive_zheng_xiao"),
    UiApiWebTestCases("lottery_order_positive_chief_shaw"),
    UiApiWebTestCases("lottery_order_positive_special_one_number"),
    UiApiWebTestCases("lottery_order_positive_special_one_two_sides"),
    UiApiWebTestCases("lottery_order_positive_special_one_color"),
    UiApiWebTestCases("lottery_order_positive_special_two_number"),
    UiApiWebTestCases("lottery_order_positive_special_two_two_sides"),
    UiApiWebTestCases("lottery_order_positive_special_two_color"),
    UiApiWebTestCases("lottery_order_positive_special_three_number"),
    UiApiWebTestCases("lottery_order_positive_special_three_two_sides"),
    UiApiWebTestCases("lottery_order_positive_special_three_color"),
    UiApiWebTestCases("lottery_order_positive_special_four_number"),
    UiApiWebTestCases("lottery_order_positive_special_four_two_sides"),
    UiApiWebTestCases("lottery_order_positive_special_four_color"),
    UiApiWebTestCases("lottery_order_positive_special_five_number"),
    UiApiWebTestCases("lottery_order_positive_special_five_two_sides"),
    UiApiWebTestCases("lottery_order_positive_special_five_color"),
    UiApiWebTestCases("lottery_order_positive_special_six_number"),
    UiApiWebTestCases("lottery_order_positive_special_six_two_sides"),
    UiApiWebTestCases("lottery_order_positive_special_six_color"),
    UiApiWebTestCases("lottery_order_pinshaw_tail_one_tail"),
    UiApiWebTestCases("lottery_order_pinshaw_tail_yi_xiao"),
    UiApiWebTestCases("lottery_order_lian_xiao_lian_tail_two_tail"),
    UiApiWebTestCases("lottery_order_lian_xiao_lian_tail_three_tail"),
    UiApiWebTestCases("lottery_order_lian_xiao_lian_tail_four_tail"),
    UiApiWebTestCases("lottery_order_lian_xiao_lian_tail_five_tail"),
    UiApiWebTestCases("lottery_order_lian_xiao_lian_tail_two_xiao"),
    UiApiWebTestCases("lottery_order_lian_xiao_lian_tail_three_xiao"),
    UiApiWebTestCases("lottery_order_lian_xiao_lian_tail_four_xiao"),
    UiApiWebTestCases("lottery_order_lian_xiao_lian_tail_five_xiao"),
    UiApiWebTestCases("lottery_order_consecutive_number_special"),
    UiApiWebTestCases("lottery_order_consecutive_number_two_special_win"),
    UiApiWebTestCases("lottery_order_consecutive_number_two_all_win"),
    UiApiWebTestCases("lottery_order_consecutive_number_three_win_two"),
    UiApiWebTestCases("lottery_order_consecutive_number_three_all_win"),
    UiApiWebTestCases("lottery_order_consecutive_number_four_all_win"),
    UiApiWebTestCases("lottery_order_not_win_five_not_win"),
    UiApiWebTestCases("lottery_order_not_win_six_not_win"),
    UiApiWebTestCases("lottery_order_not_win_seven_not_win"),
    UiApiWebTestCases("lottery_order_not_win_eight_not_win"),
    UiApiWebTestCases("lottery_order_not_win_nine_not_win"),
    UiApiWebTestCases("lottery_order_not_win_ten_not_win"),
    UiApiWebTestCases("lottery_order_not_win_eleven_not_win"),
    UiApiWebTestCases("lottery_order_not_win_twelve_not_win"),
    UiApiWebTestCases("lottery_order_sb_sb"),
    UiApiWebTestCases("lottery_order_sb_bb"),
    UiApiWebTestCases("lottery_order_sb_bbb"),
    UiApiWebTestCases("lottery_order_sb_seven_sb"),
    UiApiWebTestCases("lottery_order_win_five_win_one"),
    UiApiWebTestCases("lottery_order_win_six_win_one"),
    UiApiWebTestCases("lottery_order_win_seven_win_one"),
    UiApiWebTestCases("lottery_order_win_eight_win_one"),
    UiApiWebTestCases("lottery_order_win_nine_win_one"),
    UiApiWebTestCases("lottery_order_win_ten_win_one"),
    UiApiWebTestCases("ssc_order_two_sides_ten_thousand"),
    UiApiWebTestCases("ssc_order_two_sides_thousand"),
    UiApiWebTestCases("ssc_order_two_sides_hundred"),
    UiApiWebTestCases("ssc_order_two_sides_ten"),
    UiApiWebTestCases("ssc_order_two_sides_one"),
    UiApiWebTestCases("ssc_order_sum"),
    UiApiWebTestCases("ssc_order_sum_mantissa"),
    UiApiWebTestCases("ssc_order_long_hu_he"),
    UiApiWebTestCases("ssc_order_sum_five_characters"),
    UiApiWebTestCases("ssc_order_sum_top_three"),
    UiApiWebTestCases("ssc_order_sum_middle_three"),
    UiApiWebTestCases("ssc_order_sum_last_three"),
    UiApiWebTestCases("ssc_order_sum_ten_thousand_thousand"),
    UiApiWebTestCases("ssc_order_sum_ten_thousand_hundred"),
    UiApiWebTestCases("ssc_order_sum_ten_thousand_ten"),
    UiApiWebTestCases("ssc_order_sum_ten_thousand_one"),
    UiApiWebTestCases("ssc_order_sum_thousand_hundred"),
    UiApiWebTestCases("ssc_order_sum_thousand_ten"),
    UiApiWebTestCases("ssc_order_sum_thousand_one"),
    UiApiWebTestCases("ssc_order_sum_hundred_ten"),
    UiApiWebTestCases("ssc_order_sum_hundred_one"),
    UiApiWebTestCases("ssc_order_sum_ten_one"),
    UiApiWebTestCases("ssc_order_sum_mantissa_five_characters"),
    UiApiWebTestCases("ssc_order_sum_mantissa_top_three"),
    UiApiWebTestCases("ssc_order_sum_mantissa_middle_three"),
    UiApiWebTestCases("ssc_order_sum_mantissa_last_three"),
    UiApiWebTestCases("ssc_order_sum_mantissa_ten_thousand_thousand"),
    UiApiWebTestCases("ssc_order_sum_mantissa_ten_thousand_hundred"),
    UiApiWebTestCases("ssc_order_sum_mantissa_ten_thousand_ten"),
    UiApiWebTestCases("ssc_order_sum_mantissa_ten_thousand_one"),
    UiApiWebTestCases("ssc_order_sum_mantissa_thousand_hundred"),
    UiApiWebTestCases("ssc_order_sum_mantissa_thousand_ten"),
    UiApiWebTestCases("ssc_order_sum_mantissa_thousand_one"),
    UiApiWebTestCases("ssc_order_sum_mantissa_hundred_ten"),
    UiApiWebTestCases("ssc_order_sum_mantissa_hundred_one"),
    UiApiWebTestCases("ssc_order_sum_mantissa_ten_one"),
    UiApiWebTestCases("ssc_order_choose_one_all_five"),
    UiApiWebTestCases("ssc_order_choose_one_top_three"),
    UiApiWebTestCases("ssc_order_choose_one_middle_three"),
    UiApiWebTestCases("ssc_order_choose_one_last_three"),
    UiApiWebTestCases("ssc_order_word_positioning_ten_thousand"),
    UiApiWebTestCases("ssc_order_word_positioning_thousand"),
    UiApiWebTestCases("ssc_order_word_positioning_hundred"),
    UiApiWebTestCases("ssc_order_word_positioning_ten"),
    UiApiWebTestCases("ssc_order_word_positioning_one"),
    UiApiWebTestCases("ssc_order_twoword_positioning_ten_thousand_thousand"),
    UiApiWebTestCases("ssc_order_twoword_positioning_ten_thousand_hundred"),
    UiApiWebTestCases("ssc_order_twoword_positioning_ten_thousand_ten"),
    UiApiWebTestCases("ssc_order_twoword_positioning_ten_thousand_one"),
    UiApiWebTestCases("ssc_order_twoword_positioning_thousand_hundred"),
    UiApiWebTestCases("ssc_order_twoword_positioning_thousand_ten"),
    UiApiWebTestCases("ssc_order_twoword_positioning_thousand_one"),
    UiApiWebTestCases("ssc_order_twoword_positioning_hundred_ten"),
    UiApiWebTestCases("ssc_order_twoword_positioning_hundred_one"),
    UiApiWebTestCases("ssc_order_twoword_positioning_ten_one"),
    UiApiWebTestCases("ssc_order_threeword_positioning_top_three"),
    UiApiWebTestCases("ssc_order_threeword_positioning_middle_three"),
    UiApiWebTestCases("ssc_order_threeword_positioning_last_three"),
    UiApiWebTestCases("ssc_order_fiveword_positioning"),
    UiApiWebTestCases("ssc_order_group_three_top_three"),
    UiApiWebTestCases("ssc_order_group_three_middle_three"),
    UiApiWebTestCases("ssc_order_group_three_last_three"),
    UiApiWebTestCases("ssc_order_group_six_top_three"),
    UiApiWebTestCases("ssc_order_group_six_middle_three"),
    UiApiWebTestCases("ssc_order_group_six_last_three"),
    UiApiWebTestCases("ssc_order_span_top_three"),
    UiApiWebTestCases("ssc_order_span_middle_three"),
    UiApiWebTestCases("ssc_order_span_last_three"),
    UiApiWebTestCases("ssc_order_special_play_top_three"),
    UiApiWebTestCases("ssc_order_special_play_middle_three"),
    UiApiWebTestCases("ssc_order_special_play_last_three"),
    UiApiWebTestCases("pk_ten_order_champion"),
    UiApiWebTestCases("pk_ten_order_runner_up"),
    UiApiWebTestCases("pk_ten_order_third_place"),
    UiApiWebTestCases("pk_ten_order_fourth_place"),
    UiApiWebTestCases("pk_ten_order_fifth_place"),
    UiApiWebTestCases("pk_ten_order_sixth_place"),
    UiApiWebTestCases("pk_ten_order_seventh_place"),
    UiApiWebTestCases("pk_ten_order_eighth_place"),
    UiApiWebTestCases("pk_ten_order_ninth_place"),
    UiApiWebTestCases("pk_ten_order_tenth_place"),
    UiApiWebTestCases("pk_ten_order_champion_and_runner_up_number"),
    UiApiWebTestCases("pk_ten_order_champion_and_runner_up_two_sides"),
    UiApiWebTestCases("pk_ten_order_champion_vs_tenth_place"),
    UiApiWebTestCases("pk_ten_order_runner_up_vs_ninth_place"),
    UiApiWebTestCases("pk_ten_order_third_vs_eighth_place"),
    UiApiWebTestCases("pk_ten_order_fourth_vs_seventh_place"),
    UiApiWebTestCases("pk_ten_order_fifth_vs_sixth_place"),
    UiApiWebTestCases("pc_egg_order_special_number"), 
    UiApiWebTestCases("pc_egg_order_special_package_three"),
    UiApiWebTestCases("pc_egg_order_two_sides"),
    UiApiWebTestCases("pc_egg_order_sb"),
    UiApiWebTestCases("pc_egg_order_special"),
    UiApiWebTestCases("eleven_choice_five_order_sum"),
    UiApiWebTestCases("eleven_choice_five_order_two_sides_first_ball"),
    UiApiWebTestCases("eleven_choice_five_order_two_sides_secend_ball"),
    UiApiWebTestCases("eleven_choice_five_order_two_sides_third_ball"),
    UiApiWebTestCases("eleven_choice_five_order_two_sides_fourth_ball"),
    UiApiWebTestCases("eleven_choice_five_order_two_sides_fifth_ball"),
    UiApiWebTestCases("eleven_choice_five_order_single_code_first_ball"),
    UiApiWebTestCases("eleven_choice_five_order_single_code_second_ball"),
    UiApiWebTestCases("eleven_choice_five_order_single_code_third_ball"),
    UiApiWebTestCases("eleven_choice_five_order_single_code_fourth_ball"),
    UiApiWebTestCases("eleven_choice_five_order_single_code_fifth_ball"),
    UiApiWebTestCases("eleven_choice_five_order_optional_one_in_one"),
    UiApiWebTestCases("eleven_choice_five_order_optional_two_in_two"),
    UiApiWebTestCases("eleven_choice_five_order_optional_three_in_three"),
    UiApiWebTestCases("eleven_choice_five_order_optional_four_in_four"),
    UiApiWebTestCases("eleven_choice_five_order_optional_five_in_five"),
    UiApiWebTestCases("eleven_choice_five_order_optional_six_in_five"),
    UiApiWebTestCases("eleven_choice_five_order_optional_seven_in_five"),
    UiApiWebTestCases("eleven_choice_five_order_optional_eight_in_five"),
    UiApiWebTestCases("eleven_choice_five_order_group_selection_top_two"),
    UiApiWebTestCases("eleven_choice_five_order_group_selection_top_three"),
    UiApiWebTestCases("eleven_choice_five_order_direct_selection_top_two"),
    UiApiWebTestCases("eleven_choice_five_order_direct_selection_top_three"),
    UiApiWebTestCases("k_three_order_two_sides"),
    UiApiWebTestCases("k_three_order_point"),
    UiApiWebTestCases("k_three_order_three_armies"),
    UiApiWebTestCases("k_three_order_round_dice"),
    UiApiWebTestCases("k_three_order_long_card"),
    UiApiWebTestCases("k_three_order_short_card"),
    UiApiWebTestCases("normal_lottery_order_word_positioning_hundred"),
    UiApiWebTestCases("normal_lottery_order_word_positioning_ten"),
    UiApiWebTestCases("normal_lottery_order_word_positioning_one"),
    UiApiWebTestCases("normal_lottery_order_two_star_group_selection"),
    UiApiWebTestCases("normal_lottery_order_three_star_group_selection_three"),
    UiApiWebTestCases("normal_lottery_order_three_star_group_selection_six"),
    UiApiWebTestCases("normal_lottery_order_word_parley"),
    UiApiWebTestCases("normal_lottery_order_sum"),
    UiApiWebTestCases("normal_lottery_order_sum_mantissa"),
    UiApiWebTestCases("normal_lottery_order_span"),
    UiApiWebTestCases("normal_lottery_order_longhuhe"),
    UiApiWebTestCases("normal_lottery_order_three_star_special"),
    UiApiWebTestCases("check_lottery_amff6_bet_record"),
    UiApiWebTestCases("check_lottery_amsf6_bet_record"),
    UiApiWebTestCases("check_lottery_amwf6_bet_record"),
    UiApiWebTestCases("check_lottery_smam6_bet_record"),
    UiApiWebTestCases("check_lottery_ff6_bet_record"),
    UiApiWebTestCases("check_lottery_sf6_bet_record"),
    UiApiWebTestCases("check_lottery_js6_bet_record"),
    UiApiWebTestCases("check_lottery_hk_bet_record"),
    UiApiWebTestCases("check_lottery_nam6_bet_record"),
    UiApiWebTestCases("check_lottery_am6_bet_record"),
    UiApiWebTestCases("check_ssc_jsssc_bet_record"),
    UiApiWebTestCases("check_ssc_wfssc_bet_record"),
    UiApiWebTestCases("check_ssc_aozxy5_bet_record"),
    UiApiWebTestCases("check_pk_ten_jspk10_bet_record"),
    UiApiWebTestCases("check_pk_ten_wfpk10_bet_record"),
    UiApiWebTestCases("check_pk_ten_aozxy10_bet_record"),
    UiApiWebTestCases("check_pk_ten_malxyft_bet_record"),
    UiApiWebTestCases("check_pc_egg_fcxy28_bet_record"),
    UiApiWebTestCases("check_pc_egg_jndbsxy28_bet_record"),
    UiApiWebTestCases("check_pc_egg_twxy28_bet_record"),
    UiApiWebTestCases("check_pc_egg_wfxy28_bet_record"),
    UiApiWebTestCases("check_eleven_choice_five_jisu11x5_bet_record"),
    UiApiWebTestCases("check_eleven_choice_five_sf11x5_bet_record"),
    UiApiWebTestCases("check_eleven_choice_five_wf11x5_bet_record"),
    UiApiWebTestCases("check_k_three_jisuk3_bet_record"),
    UiApiWebTestCases("check_k_three_sfk3_bet_record"),
    UiApiWebTestCases("check_k_three_wfk3_bet_record"),
    UiApiWebTestCases("check_normal_lottery_fc3d_bet_record"),
    UiApiWebTestCases("check_normal_lottery_pl3_bet_record"),
]

api_admin_testcase_list = [
    UiApiAdminTestCases("test_initialize_settings"),
    UiApiAdminTestCases("test_close_deposit_otp"),
    UiApiAdminTestCases("test_language_game_check"),
    UiApiAdminTestCases("delete_offer"),
    UiApiAdminTestCases("test_clear_in_shareholder"),
    UiApiAdminTestCases('test_clear_user'),
    UiApiAdminTestCases("test_set_charge"),
    UiApiAdminTestCases("test_maintain_auto"),
    UiApiAdminTestCases("test_lottery_bet_order"),
    UiApiAdminTestCases("test_admin_login"),
    UiApiAdminTestCases("test_add_bank_api"),
    UiApiAdminTestCases("test_delete_bank_account"),
    UiApiAdminTestCases("test_add_desposit_bank"),
    UiApiAdminTestCases("test_add_desposit_wechat_f2f"),
    UiApiAdminTestCases("test_add_desposit_alipay_f2f"),
    UiApiAdminTestCases("test_add_desposit_wechat_transfer"),
    UiApiAdminTestCases("test_add_desposit_alipay_transfer"),
    UiApiAdminTestCases("test_add_desposit_upi"),
    UiApiAdminTestCases("test_delete_online_merchant"),
    UiApiAdminTestCases("test_add_onlinedesposit_onlinepay"),
    UiApiAdminTestCases("test_add_onlinedesposit_unionpay"),
    UiApiAdminTestCases("test_add_onlinedesposit_jdpay"),
    UiApiAdminTestCases("test_add_onlinedesposit_kcurrency_bankscan"),
    UiApiAdminTestCases("test_add_onlinedesposit_kcurrency_banktransfer"),
    UiApiAdminTestCases("test_add_onlinedesposit_kcurrency_wechatscan"),
    UiApiAdminTestCases("test_add_onlinedesposit_kcurrency_wechattransfer"),
    UiApiAdminTestCases("test_add_onlinedesposit_kcurrency_alipayscan"),
    UiApiAdminTestCases("test_add_onlinedesposit_kcurrency_alipaytransfer"),
    UiApiAdminTestCases("test_add_onlinedesposit_kcurrency_scanpay"),
    UiApiAdminTestCases("test_add_wellpay_mybuy_bankaccount"),
    UiApiAdminTestCases("test_add_wellpay_mybuy_alipayaccount"),
    UiApiAdminTestCases("test_add_wellpay_mybuy_wechataccount"),
    UiApiAdminTestCases("test_add_wellpay_mybuy_alipayscan"),
    UiApiAdminTestCases("test_add_wellpay_mybuy_wechatscan"),
    UiApiAdminTestCases("test_delete_crypto_wallet"),
    UiApiAdminTestCases("test_add_desposit_crypto_bnb_trc"),
    UiApiAdminTestCases("test_add_desposit_crypto_bnb_erc"),
    UiApiAdminTestCases("test_add_desposit_crypto_ht_trc"),
    UiApiAdminTestCases("test_add_desposit_crypto_imtoken_trc"),
    UiApiAdminTestCases("test_add_desposit_crypto_olex_erc"),
    UiApiAdminTestCases("test_add_desposit_crypto_tokenpocket_erc"),
    UiApiAdminTestCases("test_add_rebate_and_commision"),
    UiApiAdminTestCases("test_manual_deposit"),
    UiApiAdminTestCases("test_artificial_wallet"),
    UiApiAdminTestCases("test_period_management"),
    UiApiAdminTestCases("test_handicap_management"), 
    UiApiAdminTestCases("test_betting_center_bet_rescind"),
    UiApiAdminTestCases("test_betting_center_payout_check"),
    UiApiAdminTestCases("test_betting_center_bet_validation"),
    UiApiAdminTestCases("test_mine_sweeping_hall_management"),
    UiApiAdminTestCases("test_niu_niu_hall_management"),
    UiApiAdminTestCases("test_external_platform_wallet_transfer"),
    UiApiAdminTestCases("test_external_platform_balance_inquire"),
    UiApiAdminTestCases("test_deposit_otp"),
    UiApiAdminTestCases("test_company_deposit"),
    UiApiAdminTestCases("test_online_deposit"),
    UiApiAdminTestCases("test_deposit_overview"),
    UiApiAdminTestCases("test_member_wallet"),
    UiApiAdminTestCases("test_handing_fee"),
    UiApiAdminTestCases("test_general_report"),
    UiApiAdminTestCases("test_channel_report"),
    UiApiAdminTestCases("test_daily_report"),
    UiApiAdminTestCases("test_initialize_floating"),
    # UiApiAdminTestCases("test_add_wellpay_wallet_withdraw"),  # 因暫未製作刪除出款商號，為避免一堆出款商號，故不每次都跑
    # UiApiAdminTestCases("test_add_wellpay_mybuy_withdraw"),
]


# TestCase frame add
suite = unittest.TestSuite()

if __name__ == "__main__":
    env = 'uat'
    gl._init()
    
    # 以CMD方式執行
    if len(sys.argv) == 1:
        pass
    elif len(sys.argv) > 2:
        data = sys.argv[4].split(',,')
        env = data[0]
        brand = data[1]
        user = data[2]
        push = bool(data[3])

    gl.set_value('ENV', env)
    gl.set_value('BRAND', brand)
    gl.set_value('USER', int(user))

    # for jira config
    gl.set_value('TEST_TYPE', test_type)
    BaseKey().get_jira_data()
    gl.set_value('PUSH', push)

    # TestCase add

    suite.addTests(api_admin_testcase_list)
    suite.addTests(api_web_testcase_list)
    


    # RuningTest
    Utils.unittest_xml(suite)
    